## YAML Template.
---
server:
  port: 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=api/v1/product/**
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=api/v1/order/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost